### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by mark0978** [SmileyChris/django-easysettings#3]
I understand the idea of making configuration settings more regular (models are in the models.py, views in views.py, configuration is in conf.py....)  But I don't understand how easysettings helps with anything other than that....

Part of the problem with django settings is that everything is essentially dumped into a single namespace and if I have say 4 separate settings, I end up with

MODULE_NAME_SETTING_NAME_1 = Value1
MODULE_NAME_SETTING_NAME_2 = Value2
MODULE_NAME_SETTING_NAME_3 = Value3
MODULE_NAME_SETTING_NAME_4 = Value4

easysettings seems to move the defaults to conf.py, but does nothing about grouping all the settings for MODULE_NAME into one spot.  It seems like easysettings could be used to push development more in the direction of django_debug_toolbar where there is one exposed global, with settings inside that dict.  More along the lines of

MODULE_NAME = {
   "SETTINGS_NAME_1": Value1,
   "SETTINGS_NAME_2": Value2,
   "SETTINGS_NAME_3": Value3,
   "SETTINGS_NAME_4": Value4,
}

Maybe it's just a documentation thing, but I'm not understanding why I would want to use this in its current state.

Not trying to be condescending here, I really don't understand the rationale.

**Comment by SmileyChris** [comment]
Namespacing implemented in v2
