### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by clovis1122** [SmileyChris/django-easysettings#5]
Hello!

Seems like this library does not support Python3: https://djangopackages.org/packages/p/django-easysettings/

Are there plans to support it?

**Comment by SmileyChris** [comment]
Hi @clovis1122 

Easy-settings does support Python 3, but I had neglected to add the trove classifiers to show it. I've just released v2.0.1 with these added (and Python 3.7 and Django 2.2 to the test matrix).
